# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
env: LC_CTYPE=en_US.UTF-8
before_install:
  - gem install xcpretty
script:
- xcodebuild clean test -sdk iphonesimulator -workspace AKUTestKit.xcworkspace -scheme AKUTestKit -configuration Debug OBJROOT=build ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
