# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
env: LC_CTYPE=en_US.UTF-8
before_install:
  - gem install xcpretty
script:
- xctool test -workspace AKUTestKit.xcworkspace -scheme AKUTestKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
after_success:
  - coveralls -e Pods -e Test
